# Disabled until StorageBucket resources are enabled on GKE. See README for details
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cc-experiment-ingress
#   annotations:
#     kubernetes.io/ingress.class: gce
# spec:
#   defaultBackend:
#     resource:
#       apiGroup: k8s.example.com
#       kind: StorageBucket
#       name: config-connector-experiment
#   tls:
#     - secretName: config-connector.darklang.com-tls
