version: 2
updates:

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: nuget
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
