# CLEANUP don't delete this, it's needed for F# too. Move to apiserver directory
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: darklang-tls-ingress
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  # The default backend goes to the OCaml service (editor-deployment)
  defaultBackend:
    service:
      name: darklang-nodeport
      port:
        number: 80
  rules:
    # See
    # https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#creating_an_ingress
    # These rules are intended to enable one user onto the new F# backend, while we
    # see what works.
    - http:
        paths:
          # Testing so that any user can use these
          - path: /a-testing-fsharp/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: apiserver-service
                port:
                  number: 80

          # Api - CLEANUP remove
          - path: /api-testing-fsharp/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: apiserver-service
                port:
                  number: 80
  tls:
    - secretName: darklang.com-tls
