# CLEANUP don't delete this, it's needed for F# too. Move to apiserver directory
kind: Service
apiVersion: v1
metadata:
  name: darklang-nodeport
spec:
  # We use a nodeport because google says to: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#multiple_backend_services
  # "In the Service manifest, you must use type: NodePort"
  type: NodePort
  selector:
    app: editor-app
  ports:
    - name: darklang-nodeport-port
      protocol: TCP
      port: 80
      targetPort: http-proxy-port
