# CLEANUP: ended up using a Google-managed cert for this, so this can be removed

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: static.darklang.com-tls
  namespace: default
spec:
  secretName: static.darklang.com-tls
  dnsNames:
    - static.darklang.com
  issuerRef:
    name: letsencrypt-prod-wildcards
