kind: BackendConfig
apiVersion: cloud.google.com/v1
metadata:
  name: apiserver-service-backendconfig
  namespace: darklang
# A BackendConfig allows us to configure how a load balancer talks to a service. Note
# that the BackendConfig is for the service, not the ingress, but the ingress uses
# its configuration to determine how to run.
spec:

  healthCheck:
    requestPath: "/k8s/livenessProbe"
    type: HTTP
    port: 30192 # the nodeport from apiserver-service
    # Host is not allowed here, but it has been manually set on this healthcheck so
    # that the server can recognize this is a healthcheck an API call
    # host: gce-ingress-healthcheck
    healthyThreshold: 1
    unhealthyThreshold: 1

  logging:
    # Changing this setting didn't seem to do anything - I needed to Edit it in the
    # GCP web console (or presumably using the gcloud command line utilily)
    # Note that only a change is status is logged.
    enable: true

  # Cloud armor
  securityPolicy:
    name: apiserver-service-security-policy
