apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:
  namespace: default
spec:
  secretName: darkstaticassetscom-tls
  dnsNames:
    - darkstaticassets.com
    - '*.darkstaticassets.com'
  issuerRef:
    name: letsencrypt-prod-wildcards
