apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: darkstaticassets.com-tls
  namespace: default
spec:
  secretName: darkstaticassets.com-tls
  dnsNames:
    - darkstaticassets.com
    - '*.darkstaticassets.com'
  issuerRef:
    name: letsencrypt-prod-wildcards
