apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tunnel2-network-policy
  namespace: darklang
spec:
  podSelector:
    matchLabels:
      app:
        tunnel2-app
  policyTypes:
    - Ingress

  # Allow access from any of the code-executing apps but nowhere else
  ingress:
    - from:
        - podSelector:
            matchLabels:
              use-proxy: tunnel2
