kind: BackendConfig
apiVersion: cloud.google.com/v1
metadata:
  name: bwdserver-service-backendconfig
  namespace: darklang
spec:
  # A backendconfig allows us to configure how a load balancer talks to a service.
  # There is one healthcheck per node (VM) to add it to the service.
  healthCheck:
    requestPath: "/k8s/livenessProbe"
    type: HTTP
    port: 30212 # the nodeport from bwdserver-service
    # Host is not allowed here, but it has been manually set on this healthcheck so
    # that the server can recognize this is a healthcheck and not a granduser request
    # host: gce-ingress-healthcheck
    healthyThreshold: 1
    unhealthyThreshold: 1
  logging:
    # Changing this setting didn't seem to do anything - I needed to Edit it in the
    # GCP web console (or presumably using the gcloud command line utilily)
    # Note that only a change is status is logged.
    enable: true
