apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: "balmy-ground-195100"
    cnrm.cloud.google.com/deletion-policy: abandon
  name: "config-connector-experiment"
  namespace: default
spec:
  bucketPolicyOnly: false
  cors:
    - origin: ["*"]
      responseHeader: ["Content-Type"]
      method: ["GET"]
      maxAgeSeconds: 3600
  defaultEventBasedHold: false
  # encryption is off
  # I think there's a bug in config-connector, adding an empty list of lifecycleRules makes `kubectl diff` fail every time
  # lifecycleRule: []
  location: "US"
  # logging is off
  requesterPays: false
  resourceID: "config-connector-experiment"
  storageClass: "STANDARD"
  # retentionPolicy is off
  uniformBucketLevelAccess: true
  versioning:
    enabled: false
  website:
    mainPageSuffix: "index.html"
    notFoundPage: "404.html"
