# configconnector.yaml
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one
  # ConfigConnector resource installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
  namespace: default
spec:
  mode: cluster
  googleServiceAccount: "k8s-workload-id-svc-acct@balmy-ground-195100.iam.gserviceaccount.com"
