# See docs/custom-domains.md for more detail.

kind: ClusterRoleBinding
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
  namespace: darklang
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: darklang