# See doc at https://cert-manager.io/docs/configuration/acme/; ACME is the Let's
# Encrypt client protocol
# See docs/custom-domains.md for more detail.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: darklang
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ops@darklang.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # For staging:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: ""
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            name: darkcustomdomain-tls-ingress
            podTemplate:
              metadata:
                annotations:
                  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
