# Since the namespace has a deny-by-default networkpolicy, we need a network policy
# to allow the http01-solvers.
#
# Discussion [here](https://github.com/cert-manager/cert-manager/issues/2334), though
# I ended up not using it because we don't have a firewall set by default in the
# cert-manager namespace.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cert-manager-resolver
  namespace: darklang
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
    - Ingress
  # Only requests coming in via the nginx ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8089
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: darkcustomdomain-nginx-ingress-controller

