# Configuration for nginx-ingress-controller.
#
# We mostly use this to make the nginx controller behave the same as the gce load
# balancer.
kind: ConfigMap
apiVersion: v1
metadata:
  name: darkcustomdomain-nginx-configmap
  namespace: darklang
data:
  # Allow the "server" header
  server-tokens: "true" # Allow the "server" response header
  allow-backend-server-header: "true" # Use the backend "server" response header

  # Remove extra headers
  generate-request-id: "false" # don't add a request-id header

  location-snippet: |
    proxy_set_header "via" "nginx";
