# Configuration for nginx-ingress-controller.
#
# We mostly use this to make the nginx controller behave the same as the gce load
# balancer.
kind: ConfigMap
apiVersion: v1
metadata:
  name: darkcustomdomain-nginx-configmap
  namespace: darklang
data:
  # Allow the "server" header
  server-tokens: "true" # Allow the "server" response header
  allow-backend-server-header: "true" # Use the backend "server" response header

  # Remove extra headers
  generate-request-id: "false" # don't add a request-id header

  # CLEANUP We'd like to match the gce-ingress headers, for which we'd want to prevent
  # nginx from setting x-scheme, x-real-ip, x-forwarded-host, x-forwarded-port, x-forwarded-scheme
  # Sadly, they can't be removed in any way I tried, include lua plugin,
  # location-snippet with proxy_set_header, the proxySetHeaders setting, and
  # more_clear_headers. You can see why lua and some others don't work here:
  # https://github.com/kubernetes/ingress-nginx/blob/aa813972cbc290e44e57de6718a6ca910a7b5b25/rootfs/etc/nginx/template/nginx.tmpl#L1349

  location-snippet: |
    proxy_set_header "via" "nginx";