# Network policy for darkcustomdomain-nginx-ingress-controller
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: darkcustomdomain-nginx-network-policy
  namespace: darklang
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: darkcustomdomain-nginx-ingress-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 10254
  egress:
    # Proxy to BwdServer
    - ports:
        - protocol: TCP
          port: 11001
      to:
        - podSelector:
            matchLabels:
              app: bwdserver-app
    # http-solver pods created by cert-manager
    - ports:
        - protocol: TCP
          port: 8089
      to:
        - podSelector:
            matchLabels:
              acme.cert-manager.io/http01-solver: "true"
    # It needs access to the k8s apiserver
    - ports:
        - protocol: TCP
          port: 443
    # DNS
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
