honeycomb:
  existingSecret: honeycomb-account-credentials
  apiHost: https://api.honeycomb.io/

metrics:
  clusterName: darkcluster1
  dataset: kubernetes-metrics
  enabled: true
  metricGroups:
    - node
    - pod
    - container

watchers:

  # -------------
  # Main apps
  # -------------

  ## Garbage collector
  - labelSelector: "app=garbagecollector"
    containerName: garbagecollector-ctr
    dataset: kubernetes-garbagecollector
    parser: json
    processors:
      - sample:
          type: static
          rate: 10 # 1/10 sample rate

  ## Editor
  - labelSelector: "app=editor-app"
    containerName: bwd-ctr
    dataset: kubernetes-bwd-ocaml
    parser: json
    processors:
      - request_shape:
          field: handler_name
          patterns:
            - /api/:canvas/static_assets

  # -------------
  # Sidecars
  # -------------

  ## cloudsql-proxy (darklang namespace): does json logs
  - labelSelector: "app in (bwdserver-app, queueworker-app, exechost-app)"
    namespace: darklang
    containerName: cloudsql-proxy
    dataset: cloudsql-proxy
    parser: json

  ## cloudsql-proxy (default namespace)
  - labelSelector: "app in (editor-app, cronchecker, garbagecollector)"
    containerName: cloudsql-proxy
    dataset: cloudsql-proxy
    parser: json

  # -------------
  # ingress
  # -------------

  ## Nginx ingress controller for custom domains
  - labelSelector: "app.kubernetes.io/name=darkcustomdomain-nginx-ingress-controller"
    containerName: nginx-ingress-controller
    parser: nginx
    dataset: kubernetes-bwd-nginx
    processors:
      - request_shape:
          field: request


verbosity: info
# splitLogging directs trace, debug, info, and warn log levels to stdout
# rather than stderr.
splitLogging: false
