kind: BackendConfig
apiVersion: cloud.google.com/v1
metadata:
  name: bwdserver-service-backendconfig
  namespace: default
spec:
  # A backendconfig allows us to configure how a load balancer talks to a service.
  healthCheck:
    # Lets see how this goes for now
    requestPath: "/"
    type: HTTP
  logging:
    # Changing this setting didn't seem to do anything - I needed to Edit it in the
    # GCP web console (or presumably using the gcloud command line utilily)
    enable: true
