http-handlers:
  basic-http-handler:
    method: GET
    path: /hello/:varFromRequestPath

  # initial-load:
  #   method: GET
  #   path: /initial-load

  # add-op:
  #   method: GET
  #   path: /add-op

  # handler-traces:
  #   method: GET
  #   path: /traces-for-handler/:handlerID
