# types:

# dbs:
#   domains:
#     name:
#       type: String
#       description: Testing

# functions:

# secrets:

http-handlers:
  get-root:
    method: GET
    path: /

  get-program:
    method: GET
    path: /program

  get-trace:
    method: GET
    path: /traces/:traceId

  delete-trace:
    method: DELETE
    path: /trace/:traceId

  add-op:
    method: POST
    path: /handler/:tlid/ops