apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: builtwithdark.com-tls
  namespace: default
spec:
  secretName: builtwithdark.com-tls
  dnsNames:
    - builtwithdark.com
    - '*.builtwithdark.com'
  issuerRef:
    name: letsencrypt-prod-wildcards
