apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bwd-tls-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: bwd-tls-ip
spec:
  defaultBackend:
    service:
      name: bwd-nodeport
      port:
        number: 80
  tls:
    - secretName: builtwithdark.com-tls
