apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bwd-tls-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: bwd-tls-ip
spec:
  defaultBackend:
    service:
      name: bwd-nodeport
      port:
        number: 80
  rules:
    # See
    # https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#creating_an_ingress
    # These rules are intended to enable just the users who opt in to the new F#
    # backend, while we see what works.
    - host: trydarkfsharp.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ops-documentation.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: xtopherbrandt-calculator.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: xtopherbrandt-race-sense.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: benwaffle.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: hgad.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: juliankrispel.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: juliankrispel-rob.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: luolong.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: wiskirz.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: wiskirz-crud.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: jojolocklock.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: jojolocklock-crud.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: onurg.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: onurg-crud.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: teeks-scratchpad.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: teeks-blogless.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: teeks-blogless-sites.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: teeks-blogless-slack.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: teeks-scratchpad.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: teeks-static-assets-example.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: jagtesh.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ops-circleci.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ops-corpsite.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ops-contributors.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: xumx-sqkii.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ops-pinger.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: xtopherbrandt-skistatus.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ops-adduser.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: julius-tokimeki-unfollow.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: dungahk.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: briangreenhill.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: jec-abc.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: dmiller-replaybot.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: xtopherbrandt-avs-ifttt.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    # - host: cameron-google-cache.builtwithdark.com
    #   http:
    #     paths:
    #       - path: /*
    #         pathType: ImplementationSpecific
    #         backend:
    #           service:
    #             name: bwdserver-service
    #             port:
    #               number: 80

    - host: colinplamondon.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: janiczek-nuashworld.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: clintgibler.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: rainier.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: johnverrone-gamechanger.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: mause-banking.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: jwalter-chatters.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: sensenich-elrrqrdmigdnyhxrkjmpkodojurdgvgy.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: janiczek-ellies.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: saimiri-deployed.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: syadali-crud.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: syadali.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: ike.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

    - host: danielsokil-esf-locations.builtwithdark.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80


  tls:
    - secretName: builtwithdark.com-tls
