apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bwd-tls-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: bwd-tls-ip
spec:
  defaultBackend:
    service:
      name: bwd-nodeport
      port:
        number: 80
  rules:
    # Everyone is now on the new service. Note that we do this here rather than
    # changing the defaultBackend as when we changed over the editor/ApiServer using
    # defaultBackend, something went wrong and it wasn't clear what. We'll be
    # removing this shortly once we switch DNS over anyway.
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: bwdserver-service
                port:
                  number: 80

  tls:
    - secretName: builtwithdark.com-tls
